#!/usr/bin/env bash
# precommit-config.sh — pre-commit config selection/generation for
# scripts/adopt.sh, including the merged (monorepo) config generator.
#
# Sourced by scripts/adopt.sh — NOT self-contained. Expects the caller to
# have already defined:
#   Functions: log(), warn(), die()
#   Globals:   PROJECT_ROOT, BLUEPRINT_RESOLVED, DRY_RUN, PRECOMMIT_TEMPLATE
#
# Usage:
#   source "$BLUEPRINT_DIR/scripts/lib/precommit-config.sh"
#   generate_precommit_config "${FRAMEWORKS[@]}"

set -u

# Writes $PROJECT_ROOT/.pre-commit-config.yaml — a single-framework template
# copy, a real merged config for monorepos (or when --precommit-template
# forces it), or leaves an existing file untouched. See adopt.sh --help for
# --precommit-template's exact override semantics.
generate_precommit_config() {
  local frameworks=("$@")
  local output="$PROJECT_ROOT/.pre-commit-config.yaml"

  if [[ -f "$output" ]]; then
    log "Existing .pre-commit-config.yaml preserved"
    return
  fi

  # --precommit-template overrides auto-detection entirely. Warn (don't fail)
  # if the override doesn't match any detected framework — the user may
  # deliberately want e.g. Node linters in a Python-only repo.
  if [[ -n "$PRECOMMIT_TEMPLATE" ]]; then
    local template_matches=0
    for fw in "${frameworks[@]}"; do
      case "$PRECOMMIT_TEMPLATE:$fw" in
        python:python|python:nestjs|node:node|node:nextjs|node:nestjs) template_matches=1 ;;
        merged:*) template_matches=1 ;;
      esac
    done
    [[ $template_matches -eq 1 ]] || warn "--precommit-template $PRECOMMIT_TEMPLATE does not match detected framework(s) (${frameworks[*]}) — using it anyway since it was explicitly requested."

    if [[ "$PRECOMMIT_TEMPLATE" == "python" || "$PRECOMMIT_TEMPLATE" == "node" ]]; then
      local PC_SRC="$BLUEPRINT_RESOLVED/pre-commit/.pre-commit-config.${PRECOMMIT_TEMPLATE}.yaml"
      if [[ -f "$PC_SRC" ]]; then
        if [[ $DRY_RUN -eq 1 ]]; then
          printf '  DRY: cp %s %s (forced by --precommit-template)\n' "$PC_SRC" "$output"
        else
          cp "$PC_SRC" "$output"
        fi
      else
        die "Template not found: $PC_SRC"
      fi
      return
    fi
    # PRECOMMIT_TEMPLATE == "merged" falls through to the merge generator below,
    # forcing both has_python and has_node on regardless of detected frameworks.
  elif [[ ${#frameworks[@]} -eq 1 ]]; then
    # No override, single framework - use existing logic
    local PC_SRC=""
    case "${frameworks[0]}" in
      python) PC_SRC="$BLUEPRINT_RESOLVED/pre-commit/.pre-commit-config.python.yaml" ;;
      node|nextjs|nestjs) PC_SRC="$BLUEPRINT_RESOLVED/pre-commit/.pre-commit-config.node.yaml" ;;
    esac
    if [[ -n "$PC_SRC" && -f "$PC_SRC" ]]; then
      if [[ $DRY_RUN -eq 1 ]]; then
        printf '  DRY: cp %s %s\n' "$PC_SRC" "$output"
      else
        cp "$PC_SRC" "$output"
      fi
    fi
    return
  fi

  # Multiple frameworks (or --precommit-template merged) - generate merged config
  log "Generating merged pre-commit config${PRECOMMIT_TEMPLATE:+ (forced by --precommit-template merged)}"

  if [[ $DRY_RUN -eq 1 ]]; then
    printf '  DRY: Generate merged .pre-commit-config.yaml\n'
    return
  fi

  local has_python=0
  local has_node=0

  if [[ "$PRECOMMIT_TEMPLATE" == "merged" ]]; then
    has_python=1
    has_node=1
  else
    for fw in "${frameworks[@]}"; do
      case "$fw" in
        python|nestjs) has_python=1 ;;
        node|nextjs) has_node=1 ;;
      esac
    done
  fi

  # Detect workspace paths for filters
  local backend_path=""
  local frontend_path=""

  [[ -d "$PROJECT_ROOT/backend" ]] && backend_path="backend/"
  [[ -d "$PROJECT_ROOT/api" ]] && backend_path="${backend_path:-api/}"
  [[ -d "$PROJECT_ROOT/frontend" ]] && frontend_path="frontend/"
  [[ -d "$PROJECT_ROOT/web" ]] && frontend_path="${frontend_path:-web/}"

  cat > "$output" <<'YAML'
# Merged pre-commit configuration for monorepo
# Generated by adopt.sh
repos:
YAML

  # Python hooks
  if [[ $has_python -eq 1 ]]; then
    cat >> "$output" <<YAML
  # Python hooks${backend_path:+ (${backend_path} only)}
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
${backend_path:+        files: ^${backend_path}}

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
${backend_path:+        files: ^${backend_path}}

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
${backend_path:+        files: ^${backend_path}}

YAML
  fi

  # Node hooks
  if [[ $has_node -eq 1 ]]; then
    cat >> "$output" <<YAML
  # JavaScript/TypeScript hooks${frontend_path:+ (${frontend_path} only)}
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
${frontend_path:+        files: ^${frontend_path}}
        types: [file]
        types_or: [javascript, jsx, ts, tsx]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0
    hooks:
      - id: prettier
${frontend_path:+        files: ^${frontend_path}}
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]

YAML
  fi

  # Shared hooks
  cat >> "$output" <<'YAML'
  # Shared hooks (all files)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
YAML
}
