#!/usr/bin/env bash
# update-docs.sh — the single integration seam for the auto-docs pipeline.
#
# Every trigger (GitHub Actions, n8n, the orchestrator, cron, or a local
# post-merge hook) computes a commit range and calls this wrapper; it runs
# /update-docs headless and delivers a DRAFT PR on a docs/auto-update-<ts>
# branch. The collector/extractor/command never change per trigger.
#
# Usage:
#   ./scripts/update-docs.sh --range <A>..<B>      # explicit range
#   ./scripts/update-docs.sh --ci                  # read github.event before/after
#   ./scripts/update-docs.sh --local               # default HEAD~1..HEAD
#   ./scripts/update-docs.sh --range A..B --dry-run # print the git/gh commands only

set -euo pipefail

BLUEPRINT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$BLUEPRINT_DIR"
export PATH="/usr/local/bin:/opt/homebrew/bin:$HOME/.local/bin:$PATH"

RANGE=""
DRY_RUN=0
MODE="local"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --range) RANGE="$2"; shift 2 ;;
    --ci)    MODE="ci"; shift ;;
    --local) MODE="local"; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

# Resolve the range.
if [[ -z "$RANGE" ]]; then
  if [[ "$MODE" == "ci" && -n "${GITHUB_EVENT_BEFORE:-}" && -n "${GITHUB_SHA:-}" ]]; then
    BEFORE="$GITHUB_EVENT_BEFORE"
    # New-branch / force-push guard: all-zeros before -> fall back to last commit.
    if [[ "$BEFORE" =~ ^0+$ ]]; then RANGE="HEAD~1..HEAD"; else RANGE="${BEFORE}..${GITHUB_SHA}"; fi
  else
    RANGE="HEAD~1..HEAD"
  fi
fi

CLAUDE_BIN="$(command -v claude || true)"
if [[ -z "$CLAUDE_BIN" ]]; then echo "error: 'claude' CLI not found on PATH" >&2; exit 127; fi

TS="$(date -u +%Y%m%d-%H%M%S)"
BRANCH="docs/auto-update-${TS}"
BASE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

run() { if [[ $DRY_RUN -eq 1 ]]; then printf 'DRY: %s\n' "$*"; else eval "$@"; fi; }

mkdir -p reports
echo "===== update-docs: $(date -u +%Y-%m-%dT%H:%M:%SZ) range=$RANGE base=$BASE_BRANCH =====" | tee -a reports/update-docs.log

# Run the doc generation headless. In dry-run, ask the command to report only.
if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: $CLAUDE_BIN -p \"/update-docs --report-only --range $RANGE\""
else
  "$CLAUDE_BIN" -p "/update-docs --range $RANGE" >> reports/update-docs.log 2>&1 || true
fi

# Deliver only if /update-docs actually wrote something under docs/.
if [[ $DRY_RUN -eq 0 ]] && git diff --quiet -- docs/; then
  echo "No docs changes — nothing to deliver." | tee -a reports/update-docs.log
  exit 0
fi

run "git checkout -B \"$BRANCH\""
run "git add docs/"
run "git -c user.name='claude-docs-bot' -c user.email='noreply@anthropic.com' commit -m \"docs: auto-update for $RANGE [skip ci]\" -m \"Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>\""
run "git push -u origin \"$BRANCH\""

# Reuse an existing open PR for this base if present (idempotent), else create one.
if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: gh pr create --base \"$BASE_BRANCH\" --head \"$BRANCH\" --draft --title 'docs: auto-update' --body '...'"
else
  gh pr create --base "$BASE_BRANCH" --head "$BRANCH" --draft \
    --title "docs: auto-update for merge to $BASE_BRANCH" \
    --body "Auto-generated by \`/update-docs\` for range \`$RANGE\`. Deterministic inventories + incremental symbol reference + changelog. **Unreviewed — draft.**" \
    || echo "gh pr create skipped/failed (may already exist)"
fi
